linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - stylecheck
    - revive
    - exportloopref
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/traego/scaled-mcp

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - dupl
        - errcheck

run:
  timeout: 5m
  skip-dirs:
    - vendor
  modules-download-mode: readonly
